export const paths = {
  home: "/",
  login: "/login",
  register: "/register",
  dashboard: "/dashboard",
  clients: "/clientes",
  sales: "/vendas",
  installations: "/instalacoes",
  stock: "/estoque",
  history: "/historico",
  technicians: "/tecnicos",
  occurrences: "/ocorrencias",
  reports: "/relatorios",
  profile: "/profile",
  settings: "/configuracoes",
};
